/************************************************************
* name William Shelton
* user uafs415
* date 5 November 2021
* assign Problem Set 5
************************************************************/



import com.ibm.db2.jcc.am.Connection;
import com.ibm.db2.jcc.am.ResultSet;
import java.awt.BorderLayout;
import static java.awt.SystemColor.window;
import java.awt.event.KeyEvent;
import java.io.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author William Shelton
 */
public class PS4App extends javax.swing.JFrame {
    
    
    /**
     * Creates new form PS4App
     */
    public PS4App() {
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        CashOrCredit = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameBake = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DescBake = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PriceBake = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RemoveBake = new javax.swing.JTextField();
        RemoveButton = new javax.swing.JButton();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        RefreshButton = new javax.swing.JButton();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        BakeTable = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        AddCust = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ZIP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        CustId = new javax.swing.JTextField();
        RemoveCust = new javax.swing.JButton();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustTable = new javax.swing.JTable();
        RefreshButton2 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        NameInv = new javax.swing.JTextField();
        InvD = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        AMount = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        AddInv = new javax.swing.JButton();
        jTabbedPane22 = new javax.swing.JTabbedPane();
        jPanel20 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        InvId = new javax.swing.JTextField();
        RemoveInv = new javax.swing.JButton();
        jTabbedPane23 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jTabbedPane24 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        InvTable = new javax.swing.JTable();
        RefreshButton3 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jTabbedPane18 = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tables = new javax.swing.JTable();
        DisplayReceipt = new javax.swing.JButton();
        Former = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        QTYNeed = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Paymentamount = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        CustName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ValidationCheck = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        ItemName = new javax.swing.JTextField();
        Cash = new javax.swing.JRadioButton();
        Credit = new javax.swing.JRadioButton();
        SearchBar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setName(""); // NOI18N

        jLabel1.setText("Name:");

        jLabel2.setText("Description:");

        jLabel3.setText("Price:");

        AddButton.setText("Add Item");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(NameBake, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PriceBake, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 309, Short.MAX_VALUE))
                            .addComponent(DescBake)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameBake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PriceBake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescBake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddButton)
                .addGap(38, 38, 38))
        );

        jTabbedPane4.addTab("Add new Bakery Item", jPanel2);

        jLabel4.setText("Item ID:");

        RemoveButton.setText("Removed Item");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveBake, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 593, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RemoveButton)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveBake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemoveButton)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Remove Item", jPanel3);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        BakeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BakeTable);

        jTabbedPane7.addTab("Bakery Items", jScrollPane1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(RefreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("List Of Bakery Items", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane4)
                    .addComponent(jTabbedPane5)
                    .addComponent(jTabbedPane6))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Bakery Items", jPanel1);

        jLabel5.setText("First Name:");

        jLabel6.setText("Last Name:");

        jLabel7.setText("Address:");

        AddCust.setText("Add Customer");
        AddCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustActionPerformed(evt);
            }
        });

        jLabel9.setText("City:");

        jLabel10.setText("State:");

        jLabel11.setText("ZIP:");

        jLabel12.setText("Username:");

        jLabel13.setText("Password:");

        jLabel14.setText("Phone:");

        jLabel15.setText("Email:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Lname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ZIP, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddCust)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(203, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCust)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Add new Customer", jPanel6);

        jLabel8.setText("Customer ID:");

        RemoveCust.setText("Removed Customer");
        RemoveCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveCustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(RemoveCust))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemoveCust)
                .addContainerGap())
        );

        jTabbedPane9.addTab("Remove Customer", jPanel7);

        CustTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(CustTable);

        jTabbedPane11.addTab("Customers", jScrollPane2);

        RefreshButton2.setText("Refresh");
        RefreshButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefreshButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(RefreshButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jTabbedPane10.addTab("Customer List", jPanel8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jTabbedPane10)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTabbedPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("", jPanel5);

        jTabbedPane1.addTab("Customers", jTabbedPane2);

        jLabel59.setText("Name:");

        jLabel60.setText("Description:");

        jLabel61.setText("Quantity:");

        jLabel62.setText("Amount:");

        jLabel63.setText("Price:");

        AddInv.setText("Add Item");
        AddInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameInv, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AMount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InvD, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Price)
                    .addComponent(Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddInv)
                .addGap(21, 21, 21))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NameInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel62)
                        .addComponent(AMount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddInv)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane17.addTab("Add new Item", jPanel18);

        jLabel64.setText("Item ID:");

        RemoveInv.setText("Remove Item");
        RemoveInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)
                .addComponent(RemoveInv)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemoveInv)
                .addGap(19, 19, 19))
        );

        jTabbedPane22.addTab("Remove Item", jPanel20);

        InvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(InvTable);

        jTabbedPane24.addTab("Inventory", jScrollPane3);

        RefreshButton3.setText("Refresh");
        RefreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefreshButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RefreshButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
        );

        jTabbedPane23.addTab("Inventory List", jPanel21);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane17)
                    .addComponent(jTabbedPane22)
                    .addComponent(jTabbedPane23))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane3.addTab("", jPanel13);

        jTabbedPane1.addTab("Inventory", jTabbedPane3);

        Tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(Tables);

        DisplayReceipt.setText("Display");
        DisplayReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayReceiptActionPerformed(evt);
            }
        });

        Former.setText("Previous Orders");
        Former.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DisplayReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Former))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayReceipt)
                    .addComponent(Former)))
        );

        jTabbedPane18.addTab("Tables", jPanel19);

        jLabel29.setText("Quantity:");

        QTYNeed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QTYNeedKeyPressed(evt);
            }
        });

        jLabel31.setText("Payment Amount:");

        Paymentamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PaymentamountKeyPressed(evt);
            }
        });

        jLabel32.setText("CustomerName:");

        CustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustNameActionPerformed(evt);
            }
        });
        CustName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CustNameKeyPressed(evt);
            }
        });

        ValidationCheck.setColumns(20);
        ValidationCheck.setRows(5);
        jScrollPane4.setViewportView(ValidationCheck);

        jLabel16.setText("ItemName:");

        ItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ItemNameKeyPressed(evt);
            }
        });

        CashOrCredit.add(Cash);
        Cash.setText("Cash");

        CashOrCredit.add(Credit);
        Credit.setText("Credit");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(Paymentamount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QTYNeed, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(QTYNeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(CustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(Paymentamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Credit))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap())
        );

        SearchBar.setText("Search");
        SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchBarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane18)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Order Details & Recipe", jPanel16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        
        BakeryItemsDAO a = new BakeryItemsDAO(); 
        BakeryItems b = new BakeryItems();
        
        b.setBakeryItemName(NameBake.getText());
        b.setBakeryItemDesciption(DescBake.getText());
        b.setBakeryItemPrice(Double.parseDouble(PriceBake.getText()));
        
        a.insert(b);         
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        
        BakeryItemsDAO a = new BakeryItemsDAO(); 
        BakeryItems b = new BakeryItems();
        
        int id = Integer.parseInt(RemoveBake.getText());
        
        b.setBakeryItemId(id);
        
        a.delete(b);
        
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        
        JTable table = new JTable();

        DefaultTableModel model2 = new DefaultTableModel();

        BakeryItemsDAO a = new BakeryItemsDAO();
        
        model2.setNumRows(0);

        Object[] columnsName = new Object[4];
        
        columnsName[0] = "BakeryItemID";
        columnsName[1] = "BakeryItemName";
        columnsName[2] = "BakeryItemDescription";
        columnsName[3] = "BakeryItemPrice";
        
        model2.setColumnIdentifiers(columnsName);

        List <BakeryItems> items = a.getItem();

        Object[] rowData = new Object[4];

        for(int i = 0; i < items.size(); i++) {
            
            rowData[0] = items.get(i).getBakeryItemId();
            rowData[1] = items.get(i).getBakeryItemName();
            rowData[2] = items.get(i).getBakeryItemDesciption();
            rowData[3] = items.get(i).getBakeryItemPrice();

            model2.addRow(rowData);

        }

        BakeTable.setModel(model2);
        
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void AddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustActionPerformed
       
        CustomerDAO a = new CustomerDAO(); 
        CustomerDAO b = new CustomerDAO();
        
        b.setFName(Fname.getText());
        b.setLName(Lname.getText());
        b.setAddress(Address.getText());
        b.setPhone(phone.getText());
        b.setCity(City.getText());
        b.setState(State.getText());
        b.setZip(ZIP.getText());
        b.setEmail(Email.getText());
        b.setUser(Username.getText());
        b.setPass(Password.getText());
        
        a.insert(b);
        
    }//GEN-LAST:event_AddCustActionPerformed

    private void RefreshButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButton2ActionPerformed
        
        JTable table = new JTable();
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.setNumRows(0);

        CustomerDAO a = new CustomerDAO();
        Encrypt b = new Encrypt();

        Object[] columnsName = new Object[11];
        
        columnsName[0] = "CustomerId";
        columnsName[1] = "CustomerFirstName";
        columnsName[2] = "CustomerLastName";
        columnsName[3] = "CustomerAddress";
        columnsName[4] = "CustomerCity";
        columnsName[5] = "CustomerState";
        columnsName[6] = "CustomerZIP";
        columnsName[7] = "CustomerEmail";
        columnsName[8] = "CustomerPhone";
        columnsName[9] = "CustomerUsername";
        columnsName[10] = "CustomerPassword";
        
        model.setColumnIdentifiers(columnsName);

        List <Customers> items = a.getItem();

        Object[] rowData = new Object[11];

        for(int i = 0; i < items.size(); i++) {
            
            rowData[0] = items.get(i).getCustomerId();
            rowData[1] = items.get(i).getFName();
            rowData[2] = items.get(i).getLName();
            rowData[3] = items.get(i).getAddress();
            rowData[4] = items.get(i).getCity();
            rowData[5] = items.get(i).getState();
            rowData[6] = items.get(i).getZip();
            rowData[7] = items.get(i).getEmail();
            rowData[8] = items.get(i).getPhone();
            rowData[9] = items.get(i).getUser();
            rowData[10] = b.encryptString(items.get(i).getPass());

            model.addRow(rowData);

        }

        CustTable.setModel(model);
        
        CustTable.setAutoResizeMode(CustTable.AUTO_RESIZE_OFF);
        
        
        
    }//GEN-LAST:event_RefreshButton2ActionPerformed

    private void RemoveCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveCustActionPerformed
        
        CustomerDAO a = new CustomerDAO(); 
        CustomerDAO b = new CustomerDAO();
        
        int id = Integer.parseInt(CustId.getText());
        
        b.setCustomerId(id);
        
        a.delete(b);
        
    }//GEN-LAST:event_RemoveCustActionPerformed

    private void RemoveInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveInvActionPerformed
        
        InventoryDAO a = new InventoryDAO(); 
        InventoryDAO b = new InventoryDAO();
        
        int id = Integer.parseInt(InvId.getText());
        
        b.setInventoryId(id);
        
        a.delete(b);
        
    }//GEN-LAST:event_RemoveInvActionPerformed

    private void RefreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButton3ActionPerformed
        
        JTable table = new JTable();

        DefaultTableModel model3 = new DefaultTableModel();

        InventoryDAO a = new InventoryDAO();
        
        model3.setNumRows(0);

        Object[] columnsName = new Object[6];
        
        columnsName[0] = "InventoryID";
        columnsName[1] = "InventoryName";
        columnsName[2] = "InventoryDescription";
        columnsName[3] = "InventoryQuantityOnHand";
        columnsName[4] = "InventoryReorderedAmount";
        columnsName[5] = "InventoryReorderedPrice";
        
        model3.setColumnIdentifiers(columnsName);

        List <Inventory> items = a.getItem();

        Object[] rowData = new Object[6];

        for(int i = 0; i < items.size(); i++) {
            
            rowData[0] = items.get(i).getInventoryId();
            rowData[1] = items.get(i).getInventoryName();
            rowData[2] = items.get(i).getInventoryDescription();
            rowData[3] = items.get(i).getQuantityOnHand();
            rowData[4] = items.get(i).getReorderedAmount();
            rowData[5] = items.get(i).getReorderedPrice();

            model3.addRow(rowData);

        }

        InvTable.setModel(model3);
        
    }//GEN-LAST:event_RefreshButton3ActionPerformed

    private void AddInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInvActionPerformed

        InventoryDAO a = new InventoryDAO();
        InventoryDAO b = new InventoryDAO();

        b.setInventoryName(NameInv.getText());
        b.setInventoryDescription(InvD.getText());
        b.setQuantityOnHand(Integer.parseInt(Quantity.getText()));
        b.setReorderedAmount(Integer.parseInt(AMount.getText()));
        b.setReorderedPrice(Double.parseDouble(Price.getText()));

        a.insert(b);

    }//GEN-LAST:event_AddInvActionPerformed

    private void QTYNeedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QTYNeedKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            
            Inventory d = new Inventory();
            InventoryDAO b = new InventoryDAO();
            Recipe e = new Recipe();
            Recipe g = new Recipe();
            RecipeDAO a = new RecipeDAO();
            BakeryItems c = new BakeryItems();
            ReceiptDAO f = new ReceiptDAO();
            
            e.setQtyNeeded(Integer.parseInt(QTYNeed.getText()));
            g.setQtyNeeded(Integer.parseInt(QTYNeed.getText()));
            c.setBakeryItemName(ItemName.getText());
            e.setQtyNeeded(Integer.parseInt(QTYNeed.getText()));
            
            if(ItemName.getText().equals("Pita")) { 
                a.insertPita(e,c);
            } else if(ItemName.getText().equals("Sourdough")) {
                a.insertSour(e,c);
            } else if(ItemName.getText().equals("Cherry Pie")) {
                a.insertCherry(e,c);
            } 
            
           //Pita 
            DefaultTableModel model12 = new DefaultTableModel();
            DefaultTableModel model13 = new DefaultTableModel();
            DefaultTableModel model14 = new DefaultTableModel();
            
           
            Object[] columnsName = new Object[1];
            Object[] columnNames = new Object[1];
            Object[] columnsNames = new Object[1];
            
            columnsName[0] = "QuantityOnHand";
            columnNames[0] = "QuantityNeeded";
            columnsNames[0] = "TotalPrice";
        
            model12.setColumnIdentifiers(columnsName);
            model13.setColumnIdentifiers(columnNames);
            model14.setColumnIdentifiers(columnsNames);

            List <Inventory> items = b.getQOHPita();
            List <Recipe> item = a.getQNeeded();
            List <AmountDue> itm = f.getPrice(c);
            
            Object[] rowData = new Object[1];
            Object[] rowsData = new Object[1];
            Object[] rowsDatas = new Object[1];

            for(int i = 0; i < items.size(); i++) {
            
                rowData[0] = items.get(i).getQuantityOnHand();
                                
            }
            
            for(int i = 0; i < item.size(); i++) {
            
                rowsData[0] = item.get(i).getQtyNeeded();
                                
            }
            
            for(int i = 0; i < itm.size(); i++) {
            
                rowsDatas[0] = itm.get(i).getTotalPrice();
                                
            } 
            //Pita
            
            //Sourdough
            DefaultTableModel model15 = new DefaultTableModel();
            DefaultTableModel model16 = new DefaultTableModel();
            DefaultTableModel model17 = new DefaultTableModel();
            
           
            Object[] columns = new Object[1];
            Object[] column = new Object[1];
            Object[] columnes = new Object[1];
            
            columns[0] = "QuantityOnHand";
            column[0] = "QuantityNeeded";
            columnes[0] = "TotalPrice";
        
            model15.setColumnIdentifiers(columns);
            model16.setColumnIdentifiers(column);
            model17.setColumnIdentifiers(columnes);

            List <Inventory> sourItems = b.getQOHSour();
            List <Recipe> sourItem = a.getQNeededSour(); 
            List <AmountDue> sourItm = f.getPrice(c);
            
            Object[] row = new Object[1];
            Object[] rows = new Object[1];
            Object[] rowes = new Object[1];

            for(int i = 0; i < sourItems.size(); i++) {
            
                row[0] = sourItems.get(i).getQuantityOnHand();
                                
            }
            
            for(int i = 0; i < sourItem.size(); i++) {
            
                rows[0] = sourItem.get(i).getQtyNeeded();
                                
            }
            
            for(int i = 0; i < sourItm.size(); i++) {
            
                rowes[0] = sourItm.get(i).getTotalPrice();
                                
            }
            //Sourdough
            
            //Cherry Pie
            DefaultTableModel model18 = new DefaultTableModel();
            DefaultTableModel model19 = new DefaultTableModel();
            DefaultTableModel model20 = new DefaultTableModel();
            
           
            Object[] Ccolumns = new Object[1];
            Object[] Ccolumn = new Object[1];
            Object[] Ccolumnes = new Object[1];
            
            Ccolumns[0] = "QuantityOnHand";
            Ccolumn[0] = "QuantityNeeded";
            Ccolumnes[0] = "TotalPrice";
        
            model18.setColumnIdentifiers(Ccolumns);
            model19.setColumnIdentifiers(Ccolumn);
            model20.setColumnIdentifiers(Ccolumnes);

            List <Inventory> cherryItems = b.getQOHCherry();
            List <Recipe> cherryItem = a.getQNeededCherry(); 
            List <AmountDue> cherryItm = f.getPrice(c);
            
            Object[] crow = new Object[1];
            Object[] crows = new Object[1];
            Object[] crowes = new Object[1];

            for(int i = 0; i < cherryItems.size(); i++) {
            
                crow[0] = cherryItems.get(i).getQuantityOnHand();
                                
            }
            
            for(int i = 0; i < cherryItem.size(); i++) {
            
                crows[0] = cherryItem.get(i).getQtyNeeded();
                                
            }
            
            for(int i = 0; i < cherryItm.size(); i++) {
            
                crowes[0] = cherryItm.get(i).getTotalPrice();
                                
            }
            //Cherry Pie
             
           if(ItemName.getText().equals("Pita")) {
               
             if((Integer.parseInt(rowData[0].toString()) - Integer.parseInt(rowsData[0].toString()) <= 0)) { 
                    ValidationCheck.append("Insufficient inventory ");
             } else if ((Double.parseDouble(rowsDatas[0].toString()) > 0)) {
                    ValidationCheck.append("Insufficiemt funds ");
             }
               else {
                 
                     b.updatePita(g); 
                   
             }
            
          }
           
          if(ItemName.getText().equals("Sourdough")) {
               
             if((Integer.parseInt(row[0].toString()) - Integer.parseInt(rows[0].toString()) <= 0)) { 
                    ValidationCheck.append("Insufficient inventory");
             } else if ((Double.parseDouble(rowes[0].toString()) > 0)) {
                    ValidationCheck.append("Insufficiemt funds");
             }
               else {
                     
                    b.updateSour(g); 
                   
             }
            
          }
          
          if(ItemName.getText().equals("Cherry Pie")) {
               
             if((Integer.parseInt(crow[0].toString()) - Integer.parseInt(crows[0].toString()) <= 0)) { 
                    ValidationCheck.append("Insufficient inventory");
             } else if ((Double.parseDouble(crowes[0].toString()) > 0)) {
                    ValidationCheck.append("Insufficiemt funds");
             }
               else {
                 
                     b.updateCherry(g); 
                     
             }
            
          }
      
      }
        
    }//GEN-LAST:event_QTYNeedKeyPressed

    private void PaymentamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaymentamountKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            Payment a = new Payment();
            PaymentDAO b = new PaymentDAO();
            Customers c = new Customers();
            BakeryItems f = new BakeryItems();
            
            Cash.setActionCommand("Cash");
            Credit.setActionCommand("Credit");
            
            if(Cash.isSelected()) {
                a.setMethod(Cash.getActionCommand());
            } else if(Credit.isSelected()) {
                a.setMethod(Credit.getActionCommand());
            }
            
            a.setPaymentAMT(Double.parseDouble(Paymentamount.getText()));
            c.setFName(CustName.getText());

            b.insertPay(a,c);
            
            Payment d = new Payment();
            PaymentDAO e = new PaymentDAO();
            
            d.setPaymentAMT(Double.parseDouble(Paymentamount.getText()));
            f.setBakeryItemName(ItemName.getText());
            
            e.update(d,f);
            
        }
        
    }//GEN-LAST:event_PaymentamountKeyPressed

    private void SearchBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchBarKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            JTable table = new JTable();

            DefaultTableModel model5 = new DefaultTableModel();
        
            model5.setNumRows(0);
        
            CustomerDAO c = new CustomerDAO();
            Customers d = new Customers();
            Encrypt a = new Encrypt();
                    
            d.setFName(SearchBar.getText());
                    
            Object[] custColumns = new Object[11];
        
            custColumns[0] = "CustomerID";
            custColumns[1] = "CustomerFirstName";
            custColumns[2] = "CustomerLastName";
            custColumns[3] = "CustomerAddress";
            custColumns[4] = "CustomerCity";
            custColumns[5] = "CustomersState";
            custColumns[6] = "CustomersZip";
            custColumns[7] = "CustomersEmail";
            custColumns[8] = "CustomerPhone";
            custColumns[9] = "CustomerUsername";
            custColumns[10] = "CustomerPassword";
            
        
            model5.setColumnIdentifiers(custColumns);
            List<Customers> cust = c.searchCustomer(d);
        
            Object[] rows = new Object[11];
        
            for(int i = 0; i < cust.size(); i++) {
            
                rows[0] = cust.get(i).getCustomerId();
                rows[1] = cust.get(i).getFName();
                rows[2] = cust.get(i).getLName();
                rows[3] = cust.get(i).getAddress();
                rows[4] = cust.get(i).getCity();
                rows[5] = cust.get(i).getState();
                rows[6] = cust.get(i).getZip();
                rows[7] = cust.get(i).getEmail();
                rows[8] = cust.get(i).getPhone();
                rows[9] = cust.get(i).getUser();
                rows[10] = a.encryptString(cust.get(i).getPass());
                            
                model5.addRow(rows);
            
            }
            
            
            Tables.setModel(model5);
        
            Tables.setAutoResizeMode(CustTable.AUTO_RESIZE_OFF);
            
        }
        
    }//GEN-LAST:event_SearchBarKeyPressed

    private void CustNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustNameKeyPressed
       
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Orders a = new Orders();
            OrdersDAO b = new OrdersDAO();
            
            Customers c = new Customers();
            
            c.setFName(CustName.getText());
          
            b.insertWzgy(a,c);
                       
        }
        
    }//GEN-LAST:event_CustNameKeyPressed

    private void CustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustNameActionPerformed

    private void ItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ItemNameKeyPressed
                
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            OrderDetails a = new OrderDetails();
            OrderDetailsDAOHERE b = new OrderDetailsDAOHERE();
            BakeryItems d = new BakeryItems();
            Customers e = new Customers();
            Receipt c = new Receipt();
            ReceiptDAO h = new ReceiptDAO();
            
            a.setQuantity(Integer.parseInt(QTYNeed.getText()));
            e.setFName(CustName.getText());
            d.setBakeryItemName(ItemName.getText());
            c.setQuantity(Integer.parseInt(QTYNeed.getText()));
            
            b.insertCherry(a,d,e);
            
            h.insertRec(e,d,c);
            
        }
        
    }//GEN-LAST:event_ItemNameKeyPressed

    private void DisplayReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayReceiptActionPerformed

            JTable table = new JTable();

            DefaultTableModel model5 = new DefaultTableModel();

            Receipt a = new Receipt();
            ReceiptDAO c = new ReceiptDAO();
            Customers d = new Customers();
        
                            
            Object[] columnsName = new Object[3];
        
            columnsName[0] = "OrderId";
            columnsName[1] = "ItemName";
            columnsName[2] = "TotalPrice";
        
            model5.setColumnIdentifiers(columnsName);

            List <Receipt> items = c.getAll();

            Object[] rowData = new Object[3];

            for(int i = 0; i < items.size(); i++) {
                
                rowData[0] = items.get(i).getOrID();
                rowData[1] = items.get(i).getItemName();
                rowData[2] = items.get(i).getItemPrice();
            
                model5.addRow(rowData);
                
            }
            
                Tables.setModel(model5);
        
    }//GEN-LAST:event_DisplayReceiptActionPerformed

    private void FormerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormerActionPerformed
       
        JTable table = new JTable();

        DefaultTableModel model10 = new DefaultTableModel();

        Receipt a = new Receipt();
        ReceiptDAO c = new ReceiptDAO();
                
        Object[] columnsName = new Object[3];
        
        columnsName[0] = "OrderId";
        columnsName[1] = "ItemName";
        columnsName[2] = "TotalPrice";
        
        model10.setColumnIdentifiers(columnsName);

        List <Receipt> items = c.getPrevious();

        Object[] rowData = new Object[3];

        for(int i = 0; i < items.size(); i++) {
            
            rowData[0] = items.get(i).getOrID();
            rowData[1] = items.get(i).getItemName();
            rowData[2] = items.get(i).getItemPrice();
            
            model10.addRow(rowData);

        }

        Tables.setModel(model10);
        
    }//GEN-LAST:event_FormerActionPerformed
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PS4App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PS4App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PS4App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PS4App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PS4App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMount;
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddCust;
    private javax.swing.JButton AddInv;
    private javax.swing.JTextField Address;
    private javax.swing.JTable BakeTable;
    private javax.swing.JRadioButton Cash;
    private javax.swing.ButtonGroup CashOrCredit;
    private javax.swing.JTextField City;
    private javax.swing.JRadioButton Credit;
    private javax.swing.JTextField CustId;
    private javax.swing.JTextField CustName;
    private javax.swing.JTable CustTable;
    private javax.swing.JTextField DescBake;
    private javax.swing.JButton DisplayReceipt;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fname;
    private javax.swing.JButton Former;
    private javax.swing.JTextField InvD;
    private javax.swing.JTextField InvId;
    private javax.swing.JTable InvTable;
    private javax.swing.JTextField ItemName;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField NameBake;
    private javax.swing.JTextField NameInv;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Paymentamount;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField PriceBake;
    private javax.swing.JTextField QTYNeed;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton RefreshButton2;
    private javax.swing.JButton RefreshButton3;
    private javax.swing.JTextField RemoveBake;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton RemoveCust;
    private javax.swing.JButton RemoveInv;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTextField State;
    private javax.swing.JTable Tables;
    private javax.swing.JTextField Username;
    private javax.swing.JTextArea ValidationCheck;
    private javax.swing.JTextField ZIP;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane18;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane22;
    private javax.swing.JTabbedPane jTabbedPane23;
    private javax.swing.JTabbedPane jTabbedPane24;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
